### ISSUE TITLE
Create user stories/historias de usuario

### ISSUE THREAD

**Issue by jmrr** [Phyton-es-mi-typo/tyempo#3]
We need to break down the problem described by our sprint epic into user stories.

[Source from the course](https://jj.github.io/curso-tdd/preso/dise%C3%B1o.html#/4/0/1)

For that: 

1. We will create a `Hx.md` within the `HU` dir in the project's root with the description of the user stories.
2. We will add one or more issues on Github with the prefix `HU-x` to start tracking their progress in the sprint.

**Comment by crisconru** [comment]
@jmrr I've converted all the US from the HU.md into issues. Check it all if you want ;-)
